services:
  # web1:
  #   image: httpd
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./html:/usr/local/apache2/htdocs
  bd:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=abc123.
    volumes:
      - ./datos:var/lib/mysql
