services:
  # web1:
  #   image: httpd
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./html:/usr/local/apache2/htdocs
  bd:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env_bd
    volumes:
      - datosbd:/var/lib/mysql
      # - .:proba
    secrets:
      - db_root_password
      - db_password
volumes:
  datosbd:
secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
